# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: broker.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'broker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62roker.proto\x12\x06pubsub\"H\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"&\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\"\x1b\n\nSubRequest\x12\r\n\x05topic\x18\x01 \x01(\t2e\n\x06\x42roker\x12\'\n\x07Publish\x12\x0f.pubsub.Message\x1a\x0b.pubsub.Ack\x12\x32\n\tSubscribe\x12\x12.pubsub.SubRequest\x1a\x0f.pubsub.Message0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'broker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=24
  _globals['_MESSAGE']._serialized_end=96
  _globals['_ACK']._serialized_start=98
  _globals['_ACK']._serialized_end=136
  _globals['_SUBREQUEST']._serialized_start=138
  _globals['_SUBREQUEST']._serialized_end=165
  _globals['_BROKER']._serialized_start=167
  _globals['_BROKER']._serialized_end=268
# @@protoc_insertion_point(module_scope)
